complexity:
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false

style:
  ForbiddenComment:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  ReturnCount:
    active: false
