name: Update kdoc

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Set up jdk
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Generate kdoc
      uses: ./.github/actions/kdoc
      with:
        token: '${{ secrets.KDOC }}'
